brews:
  - tap:
      owner: screwdriver-cd
      name: sd-local
      branch: master
    folder: Formula
    homepage: "https://github.com/screwdriver-cd/sd-local"
    description: "Screwdriver local mode."
    commit_msg_template: "[skip ci] Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install File.basename(@stable.url) => "sd-local"
    test: |
      system "#{bin}/sd-local", "--help"

builds:
  - binary: sd-local
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-X github.com/screwdriver-cd/sd-local/cmd.version={{ .Version }}"

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

universal_binaries:
- replace: false
