shared:
    image: golang
    environment:
        GOPATH: /sd/workspace

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: go mod download
            - vet: go vet ./...
            - gofmt: ret=$(find . -name '*.go' | xargs gofmt -d) && echo "$ret" && test -z "$ret"
            - gover: go version
            - test: go test -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out -coverpkg=./...
            - build: go build -a -o /dev/null
