shared:
    image: golang:1.13.6
    environment:
        GOPATH: /sd/workspace

jobs:
    test:
        requires: [~pr, ~commit]
        steps:
            - gover: go version
            - install: go mod download
            - vet: go vet ./...
            - gofmt: (! gofmt -d -s . | grep '^')
            - test: go test -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out -coverpkg=./... ./...
            - build: go build -a -o /dev/null
