# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SdLocal < Formula
  desc "Screwdriver local mode."
  homepage "https://github.com/screwdriver-cd/sd-local"
  version "1.0.52"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/sd-local/releases/download/v1.0.52/sd-local_darwin_amd64"
      sha256 "42b2a6367db12bd47ead901d503f43aae36b61aa61331f4e5d8645de91c820d7"

      def install
        bin.install File.basename(@stable.url) => "sd-local"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/screwdriver-cd/sd-local/releases/download/v1.0.52/sd-local_darwin_arm64"
      sha256 "ce74dd33f4f4c91ea07a0e964996b3c751307b6467df3792a870d4924ca88ecf"

      def install
        bin.install File.basename(@stable.url) => "sd-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/screwdriver-cd/sd-local/releases/download/v1.0.52/sd-local_linux_arm64"
      sha256 "1de6498177af356448d1c40a8e5378973dc3cad67953c7235b05b834bd09db15"

      def install
        bin.install File.basename(@stable.url) => "sd-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/screwdriver-cd/sd-local/releases/download/v1.0.52/sd-local_linux_amd64"
      sha256 "bc792a2a271440235957a122ac42789fa9c0682f853d27fee376b35e55857617"

      def install
        bin.install File.basename(@stable.url) => "sd-local"
      end
    end
  end

  test do
    system "#{bin}/sd-local", "--help"
  end
end
